services:
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
        
  account.api:
    build:
      context: .
      dockerfile: src/Account/Account.API/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./database:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/account.db
      - JwtSettings__Secret=${JWT_SECRET}
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
      
  transfers.api: 
    build:
      context: .
      dockerfile: src/Transfers/Transfers.API/Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./database:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/transfers.db
      - ServiceSettings__AccountApiUrl=http://account.api:8080
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=BankMore.API
      - JwtSettings__Audience=BankMore.Clients

volumes:
  database: